language: android
android:
 components:
  - build-tools-23.0.2
  - android-22

addons:
 apt:
  packages:
   - sshpass

before_install:
 - echo "install nodejs"
 - nvm install 8
 - npm install yarn -g
 - node --version
 - npm --version
 - nvm --version

install:
 - yarn install

script:
 - yarn relay
 - yarn build
 - rm dist/index.js
 - rm dist/tv.xml
 - mv dist/index.html .
 - yarn cordova -- --storePassword=$STORE_PWD --password=$STORE_PWD

after_success:
 - mv cordova/platforms/android/build/outputs/apk/android-release.apk ./app.apk
 - travis_wait sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./app.apk "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/$APP_NAME"

 - rm dist/config.xml
 - rm dist/cordova.html
 - mv index.html dist

 - node -p "require('./package.json').version" > dist/app.apk.version
 - mv dist $APP_NAME
 - tar cvfz $APP_NAME.tgz $APP_NAME
 - ls $APP_NAME -l
 - travis_wait sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $APP_NAME.tgz "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
 - sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "tar xvfz $DEPLOY_PATH/$APP_NAME.tgz -C $DEPLOY_PATH && rm $DEPLOY_PATH/$APP_NAME.tgz"
